package com.mimecast.robin.bots;

import com.mimecast.robin.config.server.BotConfig;
import com.mimecast.robin.config.server.EmailAnalysisBotConfig;
import com.mimecast.robin.mime.EmailParser;
import com.mimecast.robin.mime.parts.MimePart;
import com.mimecast.robin.mime.parts.TextMimePart;
import com.mimecast.robin.mx.MXResolver;
import com.mimecast.robin.mx.StrictMx;
import com.mimecast.robin.mx.assets.DnsRecord;
import com.mimecast.robin.mx.client.XBillDnsRecordClient;
import com.mimecast.robin.mx.dane.DaneChecker;
import com.mimecast.robin.mx.dane.DaneRecord;
import com.mimecast.robin.scanners.port.PortTlsChecker;
import com.mimecast.robin.scanners.port.PortTlsResult;
import com.mimecast.robin.scanners.rbl.DblChecker;
import com.mimecast.robin.scanners.rbl.DblResult;
import com.mimecast.robin.scanners.rbl.RblChecker;
import com.mimecast.robin.scanners.rbl.RblResult;
import com.mimecast.robin.smtp.MessageEnvelope;
import com.mimecast.robin.smtp.connection.Connection;
import com.mimecast.robin.smtp.session.Session;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.xbill.DNS.Address;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.util.*;

/**
 * Email infrastructure analysis bot.
 *
 * <p>Triggered by inbound mail to addresses matching the configured pattern. Analyses
 * the sending IP, domain, and authentication headers, then queues a plain-text report
 * back to the sender. All sections are individually enabled/disabled via {@code bots.json5}.
 *
 * <p>Checks performed (all configurable):
 * <ul>
 *   <li>DNSBL / IP reputation (RBL checks)</li>
 *   <li>Domain blocklist (DBL / SURBL / URIBL)</li>
 *   <li>Reverse DNS (rDNS) and Forward Confirmed rDNS (FCrDNS)</li>
 *   <li>SPF / DKIM / DMARC via Rspamd scan results</li>
 *   <li>MX records</li>
 *   <li>Port and TLS certificate health (25 / 465 / 587 / 993 / 143)</li>
 *   <li>MTA-STS policy (configurable target domain)</li>
 *   <li>DANE / TLSA records</li>
 *   <li>Rspamd spam analysis with triggered rules and scores</li>
 *   <li>Pass / Fail verdict summary</li>
 * </ul>
 */
public class EmailAnalysisBot implements BotProcessor {
    private static final Logger log = LogManager.getLogger(EmailAnalysisBot.class);

    @Override
    public void process(Connection connection, EmailParser emailParser,
                        String botAddress, BotConfig.BotDefinition botDefinition) {
        try {
            log.info("Processing email analysis bot for: {} session: {}",
                    botAddress, connection.getSession().getUID());

            String replyTo = BotReplyAddressResolver.resolveReplyAddress(connection, botAddress);
            if (replyTo == null || replyTo.isEmpty()) {
                log.warn("Cannot determine reply address for bot request from session: {}",
                        connection.getSession().getUID());
                return;
            }

            EmailAnalysisBotConfig cfg = new EmailAnalysisBotConfig(
                    botDefinition != null ? botDefinition.getMap() : null);

            String report = generateReport(connection, cfg);
            queueResponse(connection.getSession(), botAddress, replyTo, report);

            log.info("Queued analysis report to: {} session: {}",
                    replyTo, connection.getSession().getUID());
        } catch (Exception e) {
            log.error("Error in email analysis bot for: {} session: {}",
                    botAddress, connection.getSession().getUID(), e);
        }
    }

    // ── Report assembly ───────────────────────────────────────────────────────

    private String generateReport(Connection connection, EmailAnalysisBotConfig cfg) {
        StringBuilder r = new StringBuilder();
        Session session = connection.getSession();

        r.append("=".repeat(70)).append("\n");
        r.append("EMAIL INFRASTRUCTURE ANALYSIS REPORT\n");
        r.append("Generated by Robin MTA - ").append(LocalDateTime.now()).append("\n");
        r.append("Session UID: ").append(session.getUID()).append("\n");
        r.append("=".repeat(70)).append("\n\n");

        // Verdict signals collected as checks run.
        Map<String, Boolean> verdictSignals = new LinkedHashMap<>();

        if (cfg.isRblCheckEnabled())     appendRblCheck(r, session, cfg, verdictSignals);
        if (cfg.isDblCheckEnabled())     appendDblCheck(r, session, cfg, verdictSignals);
        if (cfg.isRdnsCheckEnabled())    { appendRdnsCheck(r, session); appendFcrdnsCheck(r, session); }
        if (cfg.isSpfCheckEnabled())     appendSpfCheck(r, session, verdictSignals);
        if (cfg.isDkimCheckEnabled())    appendDkimCheck(r, session, verdictSignals);
        if (cfg.isDmarcCheckEnabled())   appendDmarcCheck(r, session, verdictSignals);
        if (cfg.isMxCheckEnabled())      appendMxCheck(r, session);
        if (cfg.isPortCheckEnabled())    appendPortCheck(r, session, cfg, verdictSignals);
        if (cfg.isMtaStsCheckEnabled())  appendMtaStsCheck(r, session, cfg);
        if (cfg.isDaneCheckEnabled())    appendDaneCheck(r, session);
        if (cfg.isSpamAnalysisEnabled()) appendSpamAnalysis(r, session, verdictSignals);
        if (cfg.isVerdictEnabled())      appendVerdict(r, verdictSignals);

        r.append("\n").append("=".repeat(70)).append("\n");
        r.append("END OF REPORT\n");
        r.append("=".repeat(70)).append("\n");
        return r.toString();
    }

    // ── 1. IP DNSBL ──────────────────────────────────────────────────────────

    private void appendRblCheck(StringBuilder r, Session session, EmailAnalysisBotConfig cfg,
                                 Map<String, Boolean> verdict) {
        r.append("DNSBL Check (IP)\n").append("-".repeat(70)).append("\n");

        String ip = session.getFriendAddr();
        if (ip == null || ip.isEmpty()) {
            r.append("Sender IP: Not available\n\n");
            return;
        }
        r.append("Sender IP: ").append(ip).append("\n");

        List<RblResult> results = RblChecker.checkIpAgainstRbls(ip, cfg.getRblProviders(),
                cfg.getRblTimeoutSeconds());

        boolean anyListed = results.stream().anyMatch(RblResult::isListed);
        verdict.put("DNSBL", !anyListed);

        if (anyListed) {
            r.append("Status: BLACKLISTED\n\n").append("Listed in:\n");
            for (RblResult res : results) {
                if (res.isListed()) {
                    r.append("  - ").append(res.getRblProvider())
                     .append(" (").append(String.join(", ", res.getResponseRecords())).append(")\n");
                }
            }
        } else {
            r.append("Status: NOT BLACKLISTED\n");
        }
        r.append("\n");
    }

    // ── 2. Domain Blocklist ───────────────────────────────────────────────────

    private void appendDblCheck(StringBuilder r, Session session, EmailAnalysisBotConfig cfg,
                                  Map<String, Boolean> verdict) {
        r.append("Domain Blocklist (DBL/SURBL)\n").append("-".repeat(70)).append("\n");

        String domain = extractDomain(session);
        if (domain == null) { r.append("Cannot determine sender domain\n\n"); return; }
        r.append("Domain: ").append(domain).append("\n");

        List<DblResult> results = DblChecker.checkDomainAgainstDbls(domain, cfg.getDblProviders(),
                cfg.getDblTimeoutSeconds());

        boolean anyListed = results.stream().anyMatch(DblResult::isListed);
        verdict.put("DomainDBL", !anyListed);

        if (anyListed) {
            r.append("Status: DOMAIN LISTED\n\nListed in:\n");
            for (DblResult res : results) {
                if (res.isListed()) {
                    r.append("  - ").append(res.getDblProvider())
                     .append(" (").append(String.join(", ", res.getResponseRecords())).append(")\n");
                }
            }
        } else {
            r.append("Status: DOMAIN NOT LISTED\n");
        }
        r.append("\n");
    }

    // ── 3+4. rDNS + FCrDNS ───────────────────────────────────────────────────

    private void appendRdnsCheck(StringBuilder r, Session session) {
        r.append("Reverse DNS (rDNS)\n").append("-".repeat(70)).append("\n");
        r.append(String.format("%-20s %-50s\n", "IP", "rDNS"));
        r.append(String.format("%-20s %-50s\n",
                nvl(session.getFriendAddr(), "N/A"),
                nvl(session.getFriendRdns(), "No rDNS")));
        r.append("\n");
    }

    private void appendFcrdnsCheck(StringBuilder r, Session session) {
        r.append("Forward Confirmed Reverse DNS (FCrDNS)\n").append("-".repeat(70)).append("\n");

        String ip = session.getFriendAddr();
        String rdns = session.getFriendRdns();

        if (ip == null || rdns == null || "unknown".equals(rdns)) {
            r.append("Cannot perform FCrDNS check — missing rDNS\n\n");
            return;
        }
        try {
            String host = rdns.endsWith(".") ? rdns.substring(0, rdns.length() - 1) : rdns;
            String forwardIp = Address.getByName(host).getHostAddress();
            boolean matches = ip.equals(forwardIp);

            r.append(String.format("%-20s %-30s %-20s %-10s\n", "IP", "rDNS", "Forward IP", "Result"));
            r.append(String.format("%-20s %-30s %-20s %-10s\n",
                    ip, rdns, forwardIp, matches ? "PASS" : "FAIL"));
            if (!matches) r.append("\nWARNING: FCrDNS mismatch — forward lookup does not match sender IP.\n");
        } catch (Exception e) {
            r.append(String.format("%-20s %-30s %-20s %-10s\n", "IP", "rDNS", "Forward IP", "Result"));
            r.append(String.format("%-20s %-30s %-20s %-10s\n", ip, rdns, "Lookup failed", "ERROR"));
            log.debug("FCrDNS lookup failed for {}: {}", rdns, e.getMessage());
        }
        r.append("\n");
    }

    // ── 5. SPF ───────────────────────────────────────────────────────────────

    private void appendSpfCheck(StringBuilder r, Session session, Map<String, Boolean> verdict) {
        r.append("SPF (Sender Policy Framework)\n").append("-".repeat(70)).append("\n");

        Map<String, Object> spfData = extractRspamdSymbol(session, "R_SPF");
        if (spfData.isEmpty()) {
            r.append("SPF Check: Not performed or no data available\n\n");
            return;
        }

        String symbol = (String) spfData.get("name");
        boolean pass = symbol != null && (symbol.equals("R_SPF_ALLOW") || symbol.equals("R_SPF_NEUTRAL"));
        verdict.put("SPF", pass);

        r.append("Result: ").append(spfVerdictLabel(symbol)).append("\n");
        r.append("Symbol: ").append(nvl(symbol, "Unknown")).append("\n");

        Object raw = spfData.get("score");
        if (raw instanceof Map) {
            Object desc = ((Map<?, ?>) raw).get("description");
            if (desc != null) r.append("Details: ").append(desc).append("\n");
        }
        r.append("\n");
    }

    private static String spfVerdictLabel(String symbol) {
        if (symbol == null) return "Unknown";
        return switch (symbol) {
            case "R_SPF_ALLOW"    -> "PASS";
            case "R_SPF_NEUTRAL"  -> "NEUTRAL";
            case "R_SPF_SOFTFAIL" -> "SOFTFAIL";
            case "R_SPF_FAIL"     -> "FAIL";
            case "R_SPF_NA"       -> "NO SPF RECORD";
            case "R_SPF_DNSFAIL"  -> "DNS ERROR";
            case "R_SPF_PERMFAIL" -> "PERMFAIL";
            default               -> symbol;
        };
    }

    // ── 6. DKIM ──────────────────────────────────────────────────────────────

    private void appendDkimCheck(StringBuilder r, Session session, Map<String, Boolean> verdict) {
        r.append("DKIM (DomainKeys Identified Mail)\n").append("-".repeat(70)).append("\n");

        Map<String, Object> dkimData = extractRspamdSymbol(session, "R_DKIM");
        if (dkimData.isEmpty()) {
            r.append("DKIM Check: Not performed or no signature found\n\n");
            return;
        }

        String symbol = (String) dkimData.get("name");
        boolean pass = "R_DKIM_ALLOW".equals(symbol);
        verdict.put("DKIM", pass);

        r.append("Signature: Found\n");
        r.append("Verification: ").append(nvl(symbol, "Unknown")).append("\n");

        Object raw = dkimData.get("score");
        if (raw instanceof Map) {
            Map<?, ?> sym = (Map<?, ?>) raw;
            Object desc = sym.get("description");
            Object opts = sym.get("options");
            if (desc != null) r.append("Details: ").append(desc).append("\n");
            if (opts != null) r.append("Options: ").append(opts).append("\n");
        }
        r.append("\n");
    }

    // ── 7. DMARC ─────────────────────────────────────────────────────────────

    private void appendDmarcCheck(StringBuilder r, Session session, Map<String, Boolean> verdict) {
        r.append("DMARC (Domain-based Message Authentication)\n").append("-".repeat(70)).append("\n");

        Map<String, Object> dmarcData = extractRspamdSymbol(session, "DMARC");
        if (dmarcData.isEmpty()) {
            r.append("DMARC Check: Not performed\n");
            r.append("Error: No DMARC record found or DMARC not checked\n\n");
            return;
        }

        String symbol = (String) dmarcData.get("name");
        boolean pass = symbol != null && symbol.contains("ALLOW");
        verdict.put("DMARC", pass);

        r.append("Symbol: ").append(nvl(symbol, "Unknown")).append("\n");
        Object raw = dmarcData.get("score");
        if (raw instanceof Map) {
            Map<?, ?> sym = (Map<?, ?>) raw;
            Object desc = sym.get("description");
            Object opts = sym.get("options");
            if (desc != null) r.append("Policy: ").append(desc).append("\n");
            if (opts != null) r.append("Options: ").append(opts).append("\n");
        }
        r.append("\n");
    }

    // ── 8. MX Records ────────────────────────────────────────────────────────

    private void appendMxCheck(StringBuilder r, Session session) {
        r.append("MX Records\n").append("-".repeat(70)).append("\n");

        String domain = extractDomain(session);
        if (domain == null) { r.append("Cannot determine sender domain\n\n"); return; }
        r.append("Domain: ").append(domain).append("\n\n");

        try {
            List<DnsRecord> mxRecords = new MXResolver().resolveMx(domain);
            if (mxRecords.isEmpty()) {
                r.append("No MX records found\n");
            } else {
                r.append(String.format("%-10s %-50s\n", "Priority", "Server"));
                r.append("-".repeat(70)).append("\n");
                for (DnsRecord mx : mxRecords) {
                    r.append(String.format("%-10d %-50s\n", mx.getPriority(), mx.getValue()));
                }
            }
        } catch (Exception e) {
            r.append("Error retrieving MX records: ").append(e.getMessage()).append("\n");
        }
        r.append("\n");
    }

    // ── 9. Port / TLS ────────────────────────────────────────────────────────

    private void appendPortCheck(StringBuilder r, Session session, EmailAnalysisBotConfig cfg,
                                   Map<String, Boolean> verdict) {
        r.append("Port / TLS Check\n").append("-".repeat(70)).append("\n");

        String domain = extractDomain(session);
        if (domain == null) { r.append("Cannot determine sender domain\n\n"); return; }

        String host = resolveFirstMx(domain);
        if (host == null) host = domain;
        r.append("Host: ").append(host).append("\n\n");

        List<PortTlsResult> results = PortTlsChecker.checkPorts(host, cfg.getPortCheckPorts(),
                cfg.getPortCheckTimeoutSeconds());

        r.append(String.format("%-6s %-8s %-8s %-12s %-6s %s\n",
                "Port", "Open", "TLS", "Cert Expiry", "Days", "Cert CN"));
        r.append("-".repeat(70)).append("\n");

        boolean port25Open = true;
        for (PortTlsResult res : results) {
            String open = res.isOpen() ? "YES" : "NO";
            String tls = switch (res.getTlsStatus()) {
                case ENABLED -> "YES";
                case DISABLED -> "NO";
                case ERROR -> "ERR";
            };
            String expiry = res.getCertExpiry() != null ? res.getCertExpiry().toString() : "-";
            String days = res.getCertExpiry() != null ? String.valueOf(res.getDaysUntilExpiry()) : "-";
            String cn = extractCN(res.getCertSubject());

            r.append(String.format("%-6d %-8s %-8s %-12s %-6s %s\n",
                    res.getPort(), open, tls, expiry, days, cn));

            if (res.isCertExpiringSoon()) {
                r.append(String.format("  ⚠ WARNING: Port %d cert expires in %d days!\n",
                        res.getPort(), res.getDaysUntilExpiry()));
            }
            if (res.getPort() == 25 && !res.isOpen()) port25Open = false;
        }
        verdict.put("Ports", port25Open);
        r.append("\n");
    }

    // ── 10. MTA-STS ──────────────────────────────────────────────────────────

    private void appendMtaStsCheck(StringBuilder r, Session session, EmailAnalysisBotConfig cfg) {
        r.append("MTA-STS (Mail Transfer Agent Strict Transport Security)\n");
        r.append("-".repeat(70)).append("\n");

        // Use configured override, or fall back to sender's domain.
        String domain = cfg.getMtaStsTargetDomain();
        if (domain == null) domain = extractDomain(session);
        if (domain == null) { r.append("Cannot determine target domain\n\n"); return; }
        r.append("Domain: ").append(domain).append("\n");

        try {
            var policy = new StrictMx(domain).getPolicy();
            if (policy != null) {
                r.append("Status: ENABLED\n");
                r.append("Mode: ").append(policy.getMode()).append("\n");
                r.append("Max Age: ").append(policy.getMaxAge()).append(" seconds\n");
                List<String> masks = policy.getMxMasks();
                if (!masks.isEmpty()) {
                    r.append("Allowed MX:\n");
                    masks.forEach(m -> r.append("  - ").append(m).append("\n"));
                }
            } else {
                r.append("Status: NOT ENABLED\n");
            }
        } catch (Exception e) {
            r.append("Status: ERROR\n").append("Error: ").append(e.getMessage()).append("\n");
        }
        r.append("\n");
    }

    // ── 11. DANE ─────────────────────────────────────────────────────────────

    private void appendDaneCheck(StringBuilder r, Session session) {
        r.append("DANE (DNS-Based Authentication of Named Entities)\n");
        r.append("-".repeat(70)).append("\n");

        String domain = extractDomain(session);
        if (domain == null) { r.append("Cannot determine sender domain\n\n"); return; }
        r.append("Domain: ").append(domain).append("\n\n");

        try {
            XBillDnsRecordClient dnsClient = new XBillDnsRecordClient();
            var mxOpt = dnsClient.getMxRecords(domain);

            if (mxOpt.isEmpty() || mxOpt.get().isEmpty()) {
                r.append("No MX records — cannot check DANE\n");
            } else {
                boolean anyDane = false;
                for (DnsRecord mx : mxOpt.get()) {
                    List<DaneRecord> tlsa = DaneChecker.checkDane(mx.getValue());
                    if (!tlsa.isEmpty()) {
                        anyDane = true;
                        r.append("MX: ").append(mx.getValue()).append("\nDANE: ENABLED\n");
                        for (DaneRecord d : tlsa) {
                            r.append("  Usage: ").append(d.getUsage())
                             .append(" (").append(d.getUsageDescription()).append(")\n");
                            r.append("  Selector: ").append(d.getSelector())
                             .append(" (").append(d.getSelectorDescription()).append(")\n");
                            r.append("  Matching: ").append(d.getMatchingType())
                             .append(" (").append(d.getMatchingTypeDescription()).append(")\n");
                            String data = d.getCertificateData();
                            r.append("  Data: ").append(data.substring(0, Math.min(64, data.length()))).append("...\n");
                        }
                        r.append("\n");
                    }
                }
                if (!anyDane) r.append("DANE: NOT ENABLED\nNo TLSA records found for any MX hosts\n");
            }
        } catch (Exception e) {
            r.append("DANE: ERROR\n").append("Error: ").append(e.getMessage()).append("\n");
        }
        r.append("\n");
    }

    // ── 12. Spam Analysis ────────────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    private void appendSpamAnalysis(StringBuilder r, Session session, Map<String, Boolean> verdict) {
        r.append("Spam Analysis (Rspamd)\n").append("-".repeat(70)).append("\n");

        if (session.getEnvelopes().isEmpty()) {
            r.append("No analysis results available\n\n");
            return;
        }

        MessageEnvelope envelope = session.getEnvelopes().getLast();
        boolean found = false;

        for (Map<String, Object> result : envelope.getScanResults()) {
            if (!"rspamd".equals(result.get("scanner"))) continue;
            found = true;

            Double score = (Double) result.get("score");
            Boolean spam = (Boolean) result.get("spam");

            r.append("Spam Score: ").append(score != null ? score : "0.0").append("\n");
            r.append("Spam Status: ").append(Boolean.TRUE.equals(spam) ? "SPAM" : "NOT SPAM").append("\n\n");
            verdict.put("SpamScore", !Boolean.TRUE.equals(spam));

            Object symsObj = result.get("symbols");
            if (!(symsObj instanceof Map)) continue;
            Map<String, Object> symbols = (Map<String, Object>) symsObj;
            if (symbols.isEmpty()) continue;

            List<Map.Entry<String, Double>> nonZero = new ArrayList<>();
            List<String> zeroRules = new ArrayList<>();

            for (Map.Entry<String, Object> entry : symbols.entrySet()) {
                double symScore = 0.0;
                if (entry.getValue() instanceof Map) {
                    Object s = ((Map<?, ?>) entry.getValue()).get("score");
                    if (s instanceof Number) symScore = ((Number) s).doubleValue();
                } else if (entry.getValue() instanceof Number) {
                    symScore = ((Number) entry.getValue()).doubleValue();
                }
                if (symScore != 0.0) {
                    nonZero.add(Map.entry(entry.getKey(), symScore));
                } else {
                    zeroRules.add(entry.getKey());
                }
            }

            if (!nonZero.isEmpty()) {
                nonZero.sort((a, b) -> Double.compare(Math.abs(b.getValue()), Math.abs(a.getValue())));
                r.append("Scored Rules:\n");
                r.append(String.format("%-10s %s\n", "Score", "Rule"));
                r.append("-".repeat(50)).append("\n");
                for (var e : nonZero) {
                    String desc = "";
                    Object raw = symbols.get(e.getKey());
                    if (raw instanceof Map) {
                        Object d = ((Map<?, ?>) raw).get("description");
                        if (d != null) desc = "  // " + d;
                    }
                    r.append(String.format("%-10.2f %s%s\n", e.getValue(), e.getKey(), desc));
                }
                r.append("\n");
            }

            if (!zeroRules.isEmpty()) {
                r.append("Other rules (score 0): ").append(String.join(", ", zeroRules)).append("\n");
            }
        }

        if (!found) r.append("Status: NOT ANALYZED\nRspamd analysis was not performed\n");
        r.append("\n");
    }

    // ── 13. Verdict ───────────────────────────────────────────────────────────

    private void appendVerdict(StringBuilder r, Map<String, Boolean> signals) {
        r.append("Verdict Summary\n").append("-".repeat(70)).append("\n");
        boolean allPass = signals.values().stream().allMatch(Boolean::booleanValue);
        r.append("Overall: ").append(allPass ? "PASS" : "FAIL").append("\n\n");
        signals.forEach((check, pass) ->
                r.append(String.format("  %-20s %s\n", check + ":", pass ? "PASS" : "FAIL")));
        r.append("\n");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    private Map<String, Object> extractRspamdSymbol(Session session, String prefix) {
        if (session.getEnvelopes().isEmpty()) return Collections.emptyMap();
        MessageEnvelope env = session.getEnvelopes().getLast();

        for (Map<String, Object> result : env.getScanResults()) {
            if (!"rspamd".equals(result.get("scanner"))) continue;
            Object symsObj = result.get("symbols");
            if (!(symsObj instanceof Map)) continue;
            Map<String, Object> symbols = (Map<String, Object>) symsObj;

            for (Map.Entry<String, Object> entry : symbols.entrySet()) {
                if (entry.getKey().startsWith(prefix)) {
                    return Map.of("name", entry.getKey(), "score", entry.getValue());
                }
            }
        }
        return Collections.emptyMap();
    }

    private String extractDomain(Session session) {
        if (!session.getEnvelopes().isEmpty()) {
            String mail = session.getEnvelopes().getLast().getMail();
            if (mail != null && mail.contains("@")) {
                return mail.substring(mail.indexOf("@") + 1);
            }
        }
        return null;
    }

    private String resolveFirstMx(String domain) {
        try {
            List<DnsRecord> mxRecords = new MXResolver().resolveMx(domain);
            if (!mxRecords.isEmpty()) {
                String host = mxRecords.get(0).getValue();
                return host.endsWith(".") ? host.substring(0, host.length() - 1) : host;
            }
        } catch (Exception e) {
            log.debug("MX resolution failed for {}: {}", domain, e.getMessage());
        }
        return null;
    }

    /** Extracts CN value from an X.500 subject string like "CN=mail.example.com, O=Acme". */
    private static String extractCN(String subject) {
        if (subject == null) return "-";
        for (String part : subject.split(",")) {
            String trimmed = part.trim();
            if (trimmed.startsWith("CN=")) return trimmed.substring(3);
        }
        return truncate(subject, 30);
    }

    private static String nvl(String v, String fallback) {
        return v != null ? v : fallback;
    }

    private static String truncate(String s, int max) {
        if (s == null || s.length() <= max) return s != null ? s : "";
        return s.substring(0, max - 1) + "…";
    }

    private void queueResponse(Session session, String botAddress, String replyTo, String report) {
        try {
            List<MimePart> parts = new ArrayList<>();
            parts.add(new TextMimePart(report.getBytes(StandardCharsets.UTF_8))
                    .addHeader("Content-Type", "text/plain; charset=\"UTF-8\"")
                    .addHeader("Content-Transfer-Encoding", "8bit"));

            BotHelper.queueBotResponse(session, botAddress, replyTo,
                    "Robin Email Analysis BOT - " + session.getUID(), parts);
        } catch (IOException e) {
            log.error("Failed to queue analysis response: {}", e.getMessage(), e);
        }
    }

    @Override
    public String getName() { return "email"; }
}
